
version: '2.2'

services:

  hiker_client:
    #build:
    #  context: test_client
    user: nobody:nogroup
    image: cyberdojo/hiker-client
    init: true
    container_name: test-hiker-client
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - hiker
    #ports:
    #  - 4548:4548
    #volumes:
    #  - ./test_client:/app/test:ro


  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  hiker:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojofoundation/image_hiker
    init: true
    container_name: test-hiker-server
    stdin_open: true
    tty: true
    read_only: true
    ports:
      - 5637:5637
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - runner
      - ragger
      - languages
    #volumes:
    #  - ./test_server:/app/test:ro

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  runner:
    user: root
    image: cyberdojo/runner:latest
    init: true
    container_name: test-hiker-runner
    stdin_open: true
    tty: true
    ports:
      - 4597:4597
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ragger:
    user: nobody
    image: cyberdojo/ragger:latest
    init: true
    container_name: test-hiker-ragger
    stdin_open: true
    tty: true
    ports:
      - 5537:5537
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - runner

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  languages:
    user: nobody
    image: ${CYBER_DOJO_LANGUAGES}
    init: true
    container_name: test-hiker-languages
    stdin_open: true
    tty: true
    ports:
      - 4524:4524
    read_only: true
    tmpfs: /tmpfs
    restart: 'no'
