
version: '2.2'

services:

  hiker_client:
    #build:
    #  context: test_client
    user: nobody:nogroup
    image: cyberdojo/hiker-client
    init: true
    container_name: test-hiker-client
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on: [ hiker ]
    #ports: [ "4548:4548" ]
    #volumes: [ "./test_client:/app/test:ro" ]


  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  hiker:
    build:
      context: app
    user: nobody
    image: cyberdojofoundation/image_hiker
    init: true
    container_name: test-hiker-server
    read_only: true
    ports: [ "5637:5637" ]
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - runner
      - ragger
      - languages-start-points
    #volumes: [ "./test_server:/app/test:ro" ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  runner:
    user: root
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    init: true
    container_name: test-traffic-light-runner
    ports: [ "${CYBER_DOJO_RUNNER_PORT}:${CYBER_DOJO_RUNNER_PORT}" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ragger:
    user: nobody
    image: ${CYBER_DOJO_RAGGER_IMAGE}:${CYBER_DOJO_RAGGER_TAG}
    init: true
    container_name: test-traffic-light-ragger
    ports: [ "${CYBER_DOJO_RAGGER_PORT}:${CYBER_DOJO_RAGGER_PORT}" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on: [ runner ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  languages-start-points:
    user: nobody
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS_IMAGE}:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG}
    init: true
    container_name: test-traffic-light-languages-start-points
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    read_only: true
    tmpfs: /tmpfs
    restart: 'no'
