version: 2
jobs:
  build-publish:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            set -e
            ./pipe_build_up_test.sh
      - run:
          name: Publish on dockerhub
          command: |
            set -e
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push cyberdojofoundation/image_hiker:latest

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          filters:
            branches:
              only:
                  - master
